### ISSUE TITLE
Lav nav i headeren 

### ISSUE THREAD

**Issue by JacobSN22** [Nicekode4/DanskNaturKat#7]
nav baren skal inde holde en ul med 3 li tags der indeholder 1 a tag i hver 
Første a tag skal hedde Forside og skal linke til den første side
Anden a tag skal hedde information og skal linke til den anden side
Tredje a tag skal hedde Bestilling og skal linke til den tredje side

**Comment by RasmusDahlJensen** [comment]
Mangler aktuelle links - de inderholder placeholder lige pt.
